#!/bin/bash

# ADMIXTURE analysis across multiple K values and replicate runs
#
# This script runs ADMIXTURE repeatedly for each tested K value.
# Ten independent runs are performed for each K using a random seed.
#
# Cross-validation is enabled with --cv to provide a CV error estimate
# for each run.
#
# The default ADMIXTURE Q-file name is renamed after each run so that
# results from different K values and replicates are retained.
#
# Input:
#   - PLINK binary dataset (.bed/.bim/.fam)
#
# Output:
#   - ADMIXTURE log files
#   - Renamed Q files for each K and replicate
#   - Corresponding P files generated by ADMIXTURE

prefix=input_name

# Run 10 independent replicates for each K
for r in {1..10}; do

    # Run ADMIXTURE for K = 12 through 17
    for K in {12..17}; do

        echo "Running ADMIXTURE: K=${K}, replicate=${r}"

        admixture \
            --cv \
            -s "${RANDOM}" \
            ~/"${prefix}.bed" \
            "$K" |
            tee ~/"log${prefix}K${K}r${r}.out"

        # Rename the Q file so that the K value and replicate
        # are retained in the filename.
        mv \
            ~/"${prefix}.${K}.Q" \
            ~/"${prefix}.K${K}r${r}.Q"

    done

done
